### ISSUE TITLE
TypeError: s is not a function

### ISSUE THREAD

**Issue by twilwa** [arihanv/Shush#10]
![image](https://github.com/arihanv/Shush/assets/111034762/0c3af4fd-4244-4ec6-a022-facd5b57aea3)
hi, was trying to get this up and running locally via modal, but i'm running into this error. I'm on windows, in WSL with Ubuntu 22.04 running. I have an AMD card, but I think the compute's coming from Modal, so hopefully that's not the issue. I havent' dug into the traceback too much to try and figure out where it's coming from, but thought it might be helpful to drop off the error message anyway.

the error occurs after uploading an MP3 file via the gui on port 3000, and clicking the 'send it!' button.

**Comment by arihanv** [comment]
Hey there! Did you deploy `modal_app.py` or `shush.py`?
