### ISSUE TITLE
How do i go faster 

### ISSUE THREAD

**Issue by shrihacker** [arihanv/Shush#5]
Im using this project since it seems like a user friendly way to achieve the latencies described here https://github.com/Vaibhavs10/insanely-fast-whisper but im trying a 27 min mp3 that seems to be processing for 20+ minutes. so what can i do to debug or go faster ?

some logs I'm seeing on modal 

```

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .
*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
Received a request from Address(host='50.35.125.15', port=50528)
Request finished with status 200. (execution time: 48.7 ms, first-byte latency: 189.7 ms)
Received a request from Address(host='50.35.125.15', port=50528)
Request finished with status 200. (execution time: 46.0 ms, first-byte latency: 212.2 ms)
Received a request from Address(host='50.35.125.15', port=50528)
Request finished with status 200. (execution time: 23.4 ms, first-byte latency: 126.9 ms)
Received a request from Address(host='50.35.125.15', port=50528)
Request finished with status 200. (execution time: 32.9 ms, first-byte latency: 146.4 ms)
Received a request from Address(host='50.35.125.15', port=50528)
Request finished with status 200. (execution time: 28.2 ms, first-byte latency: 121.6 ms)
Received a request from Address(host='50.35.125.15', port=50528)
```

**Comment by arihanv** [comment]
Requests may take longer to complete when a container is not actively running, as there is some time taken for cold starts and the GPU used also matters. Other than that, there's little I can do on my end to debug or improve speeds, but it is quite strange for the request to take 20+ minutes. You may want to check out the Modal docs or HuggingFace docs.

**Comment by shrihacker** [comment]
ok actually i think I'm not attached to a a GPU here, not sure why. Here are two hints i know this is the case.

This log from Modal

`You are attempting to use Flash Attention 2.0 with a model initialized on CPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.`

and the fact that I have this screenshot that shows no GPU on my localhost bun app but on your hosted app you do have a A10 attached

![Screenshot 2023-12-02 at 9 55 07 PM](https://github.com/arihanv/Shush/assets/127572853/aa75982a-1ed5-4fd7-93b5-0f5cce2cc4f0)
![Screenshot 2023-12-02 at 9 55 21 PM](https://github.com/arihanv/Shush/assets/127572853/92b1814d-9434-493f-b4d4-a192f57cfbe5)

Any idea how I can make sure I have a GPU attached to my modal application

**Comment by arihanv** [comment]
You can view the Modal docs here: https://modal.com/docs/examples
Also, they have a slack channel and provide quick + great help to Modal users there. A link to the slack should be somewhere in the docs or website.
You should be able to answer any questions and bugs you have with Modal there!
